name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Train (fast)
        env:
          FAST_STOP_ITERS: '10'
          FAST_NUM_WORKERS: '0'
          FAST_TRAIN_BATCH: '200'
          FAST_ROLLOUT_LEN: '50'
          FAST_SMALL_MODEL: '1'
          RAY_DISABLE_MEMORY_MONITOR: '1'
        run: |
          PYTHONPATH=$PWD python -m train.train_rllib_ppo

      - name: Plot training
        run: PYTHONPATH=$PWD python -m eval.plot_training

      - name: Record random video (short)
        run: PYTHONPATH=$PWD python -m eval.record_video --max_steps 64 --out random.mp4

      - name: List artifacts
        run: ls -R runs || true && ls -l *.mp4 training_curve.png || true


